# Generated by Django 5.1.7 on 2025-04-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.TextField(max_length=10)),
                ('log_message', models.TextField(max_length=250)),
            ],
        ),
    ]
