# Generated by Django 5.1.2 on 2025-03-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_uncensoredarticles'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncensoredarticles',
            name='article_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uncensoredarticles',
            name='article_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
