# Generated by Django 5.1.2 on 2025-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_uncensoredarticles_article_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uncensoredarticles',
            name='article_status',
            field=models.CharField(default='Hakem ataması bekleniyor.', max_length=50),
        ),
    ]
