# Generated by Django 5.1.2 on 2025-03-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_uncensoredarticles_article_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sender_email', models.EmailField(max_length=254)),
                ('message_time', models.DateTimeField(auto_now_add=True)),
                ('message_title', models.CharField(max_length=50)),
                ('message_text', models.CharField(max_length=250)),
            ],
        ),
    ]
