# Generated by Django 5.1.2 on 2025-03-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-message_time'], 'verbose_name': 'Mesaj', 'verbose_name_plural': 'Mesajlar'},
        ),
        migrations.AddField(
            model_name='messages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
