# Generated by Django 5.1.7 on 2025-03-21 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0006_alter_messages_options_messages_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='uncensoredarticles',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
