# Generated by Django 5.1.7 on 2025-03-25 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_uncensoredarticles_uploaded_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_to_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=255)),
                ('article_owner', models.EmailField(max_length=254)),
                ('article_referee', models.CharField(max_length=255)),
                ('article_keywords', models.CharField(max_length=255)),
                ('article_topic', models.TextField()),
                ('article_drive_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='author.uncensoredarticles')),
            ],
        ),
    ]
