# Generated by Django 5.1.7 on 2025-03-27 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0009_rename_article_drive_id_article_to_review_article_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurredPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurred_drive_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blurred_pdf', to='author.uncensoredarticles')),
            ],
        ),
        migrations.DeleteModel(
            name='article_to_review',
        ),
    ]
