# Generated by Django 5.1.7 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0010_blurredpdf_delete_article_to_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurredpdf',
            name='is_referee_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blurredpdf',
            name='referee_name',
            field=models.TextField(default='Hakem ataması bekleniyor.', max_length=50),
        ),
    ]
