# Generated by Django 5.1.7 on 2025-03-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0011_blurredpdf_is_referee_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='is_from_author',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_text',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='message_title',
            field=models.CharField(max_length=100),
        ),
    ]
