# Generated by Django 5.1.2 on 2025-03-18 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0005_messages'),
        ('editor', '0002_delete_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_to', models.EmailField(max_length=254)),
                ('reply_subject', models.CharField(max_length=100)),
                ('reply_text', models.TextField()),
                ('reply_time', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='author.messages')),
            ],
            options={
                'verbose_name': 'Editör Yanıtı',
                'verbose_name_plural': 'Editör Yanıtları',
                'ordering': ['-reply_time'],
            },
        ),
    ]
