# Generated by Django 5.1.7 on 2025-03-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_uncensoredarticles_uploaded_at'),
        ('editor', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_keywords_json', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_data', to='author.uncensoredarticles')),
            ],
            options={
                'verbose_name': 'Makale Anahtar Kelimeleri',
                'verbose_name_plural': 'Makale Anahtar Kelimeleri',
            },
        ),
    ]
