# Generated by Django 5.1.7 on 2025-03-23 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_uncensoredarticles_uploaded_at'),
        ('editor', '0004_articlekeywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_field', models.CharField(max_length=50)),
                ('secondary_field', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scientific_field', to='author.uncensoredarticles')),
            ],
            options={
                'verbose_name': 'Bilimsel Alan',
                'verbose_name_plural': 'Bilimsel Alanlar',
            },
        ),
    ]
