# Generated by Django 5.1.7 on 2025-03-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_uncensoredarticles_uploaded_at'),
        ('editor', '0005_scientificfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlurredImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blurred_file_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bulanıklaştırılmış Dosya ID')),
                ('processing_status', models.CharField(choices=[('pending', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='İşlem Durumu')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Hata Mesajı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blurred_images', to='author.uncensoredarticles')),
            ],
            options={
                'verbose_name': 'Bulanıklaştırılmış Görüntü',
                'verbose_name_plural': 'Bulanıklaştırılmış Görüntüler',
            },
        ),
    ]
