# Generated by Django 5.1.7 on 2025-03-23 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_blurredimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientificfield',
            name='article',
        ),
        migrations.DeleteModel(
            name='BlurredImages',
        ),
        migrations.DeleteModel(
            name='ScientificField',
        ),
    ]
