# Generated by Django 5.1.7 on 2025-03-24 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_uncensoredarticles_uploaded_at'),
        ('editor', '0007_remove_scientificfield_article_delete_blurredimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlekeywords',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlekeywords',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'İşleniyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ArticleTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_topic', models.CharField(blank=True, max_length=100)),
                ('_keywords_json', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('extraction_status', models.CharField(choices=[('pending', 'İşleniyor'), ('processing', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveSmallIntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topic_data', to='author.uncensoredarticles')),
            ],
            options={
                'verbose_name': 'Makale Konusu',
                'verbose_name_plural': 'Makale Konuları',
            },
        ),
    ]
