# Generated by Django 5.1.7 on 2025-03-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0008_articlekeywords_retry_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlekeywords',
            name='retry_count',
        ),
        migrations.AlterField(
            model_name='articlekeywords',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'İşleniyor'), ('completed', 'Tamamlandı'), ('failed', 'Başarısız')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ArticleTopics',
        ),
    ]
